### ISSUE TITLE
Directory/filename parameters are not listed in -i output

### ISSUE THREAD

**Issue by minism** [Knetic/wisk#24]
To repro:
- mkdir /tmp/skeleton
- touch /tmp/skeleton/\${{=foo=}}
- wisk -i /tmp/skeleton

Expected "foo" to be printed, but is empty instead.

By the way, thanks for the awesome tool.  I was frustrated with cookiecutter and was about to build my own.  Yours does almost everything I want.

**Comment by Knetic** [comment]
Woops! I don't know how I didn't see that, but you're absolutely right. Commit 325d7b2340749b017fde0eb7a0189b90b7df5471 fixes this.

Glad you're happy with the tool, and that I'm not the only one who wasn't happy with the alternatives :P 

If it does "almost" what you want, feel free to submit feature requests or pull requests. I'm always happy to hear ideas about features which might make life easier. :+1:

**Comment by minism** [comment]
Thanks for the amazingly quick turn-around.
