### ISSUE TITLE
[FR] Implement a mode to abort if not all parameters are specified

### ISSUE THREAD

**Issue by minism** [Knetic/wisk#25]
The default behavior of using empty string for unspecified parameters is OK for personal skeletons, but becomes problematic when you want to share your templates with team members and enforce a correct directory structure.  Especially when combined with -f, because you need to manually clean up the incorrect files that were generated.

It would be nice to have a flag that aborts without creating any files if not all parameters are given.

**Comment by Knetic** [comment]
> Especially when combined with -f, because you need to manually clean up the incorrect files that were generated.

Workaround: you can use `-d` to make it delete the existing folder before it begins output. That'll remove any incorrect files.

However, I actually was a little unsatisfied with the default behavior. I always seem to generate a project a couple times, just to make sure i got the parameter right, this FR would make it a bit less messy to use a new template. This ticket motivated me to change the default behavior. Commit 89034fd714e90fbe403dc02494d09097bd9212c9 implements this.

**Comment by minism** [comment]
Sweet!
